# Generated by Django 5.1.5 on 2025-01-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
    model_name='order',
    name='delivery_option',
    field=models.CharField(
        choices=[
            ('ঢাকার ভিতরে', 'ডেলিভারি চার্জ ঢাকার ভিতরে ৭০ টাকা'),
            ('ঢাকার বাহিরে', 'ডেলিভারি চার্জ ঢাকার বাহিরে ১৩০ টাকা')
        ],
        default='ঢাকার ভিতরে',
        max_length=50,
        ),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='product',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=50),
        ),
    ]
